create schema ORD authorization dba

create table ORD.contact (
    id BIGINT generated by default as identity, 
    email VARCHAR(255),
    phone VARCHAR(255),
        primary key (id))

create table ORD.customer (
	id BIGINT generated by default as identity, 
	name VARCHAR(255),
	contact_id BIGINT,
		primary key (id))

alter table ORD.customer add constraint customerFK0 foreign key (contact_id) references contact
