drop schema DEP cascade;
create schema DEP authorization dba; 

CREATE TABLE "DEP"."UNCHANGED"
(
   ID bigint PRIMARY KEY NOT NULL,
   OK varchar(255)
)

CREATE TABLE "DEP"."AFTER"
(
   ID bigint PRIMARY KEY NOT NULL,
   NEXT varchar(25) DEFAULT 'Add me'
)


CREATE TABLE "DEP"."ADDRESS"
(
   ID bigint PRIMARY KEY NOT NULL,
   CUSTOMER_ID integer NOT NULL,
   ADDRESS char(256) DEFAULT 'Not informed'
)
;
CREATE TABLE "DEP"."CUSTOMERS"
(
   ID bigint PRIMARY KEY NOT NULL,
   NAME varchar(255),
   DATE timestamp,
   DESCRIPTION varchar(255),
   BIRTHDAY date DEFAULT CURRENT_DATE,
   RATING numeric,
   NUMBER integer,
   TEXT longvarchar
)
;
ALTER TABLE "DEP"."ADDRESS"
ADD CONSTRAINT SYS_FK_10098
FOREIGN KEY (CUSTOMER_ID)
REFERENCES "DEP"."CUSTOMERS"(ID)
;
CREATE INDEX SYS_IDX_10102 ON "DEP"."ADDRESS"(CUSTOMER_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10096_10099 ON "DEP"."ADDRESS"(ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10092_10093 ON "DEP"."CUSTOMERS"(ID)
;
