create schema ORD authorization dba

create table ORD.customer (
	id BIGINT generated by default as identity, 
	name VARCHAR(255), 
	date TIMESTAMP,
	primary key (id))

create table ORD.logging (
	id BIGINT generated by default as identity,
	idRegister BIGINT, 
	entity VARCHAR(255), 
	attribute VARCHAR(255), 
	previous VARCHAR(255), 
	current VARCHAR(255), 
	operator VARCHAR(255), 
	atimestamp TIMESTAMP,
	primary key (id))
