create schema ORD authorization dba

create table ORD.customers (
    id BIGINT generated by default as identity, 
    name VARCHAR(255),
    description VARCHAR(255), 
        primary key (id))

create table ORD.log (
    id BIGINT generated by default as identity, 
    field VARCHAR(255),
        primary key (id))