create schema ORD authorization dba

create table ORD.customers (
	id BIGINT generated by default as identity, 
	name VARCHAR(255),
	date VARCHAR(255) not null,
	genre VARCHAR(1),
	description VARCHAR(255),
    data clob,
		primary key (id))

create table ORD.orders (
    id BIGINT generated by default as identity, 
    item VARCHAR(255),
    customer_id BIGINT,
        primary key (id))
