create schema ORD authorization dba

create table ORD.users (
    id BIGINT generated by default as identity, 
    login VARCHAR(255),
        primary key (id))
        
create table ORD.projects (
    id BIGINT generated by default as identity, 
    name VARCHAR(255),
    description VARCHAR(255),
        primary key (id))
        
create table ORD.tasks (
    id BIGINT generated by default as identity, 
    name VARCHAR(255),
    time BIGINT,
        primary key (id))

create table ORD.items (
    id BIGINT generated by default as identity, 
    a BIGINT,
    b BIGINT,
        primary key (id))
