create schema ORD authorization dba
 -- tabela CUSTOMER
create table ORD.customers (
	id BIGINT generated by default as identity, name VARCHAR(255), primary key (id))
   	-- X
create table ORD.orders (id BIGINT generated by 
	default as identity, customer_id BIGINT, date TIMESTAMP, primary key (id));
create table ORD.line_items (line_number INTEGER not null, order_id BIGINT not null, product_id BIGINT, quantity INTEGER, primary key (order_id, line_number))

create table ORD.products (id BIGINT generated by default as identity, serialNumber VARCHAR(255), primary key (id))

alter table ORD.orders add constraint ordersFK0 foreign key (customer_id) references customers

alter table ORD.line_items add constraint line_itemsFK0 foreign key (product_id) references products

alter table ORD.line_items add constraint line_itemsFK1 foreign key (order_id) references orders