create schema EXE authorization dba;
create table EXE.PRO_PROJETO (PRO_ID integer generated by default as identity (start with 1), PRO_NM varchar(255), primary key (PRO_ID));
create table EXE.TAR_TAREFA (TAR_ID integer generated by default as identity (start with 1), TAR_DS varchar(255), TAR_NM varchar(255), PRO_ID integer, primary key (TAR_ID));