drop schema ORD cascade;
create schema ord authorization dba; 

CREATE TABLE "ORD"."AFTER"
(
   ID bigint PRIMARY KEY NOT NULL,
   NEXT varchar(255) DEFAULT 'Add me'
)


CREATE TABLE "ORD"."ADDRESS"
(
   ID bigint PRIMARY KEY NOT NULL,
   CUSTOMER_ID integer NOT NULL,
   ADDRESS varchar(255) DEFAULT 'Not informed'
)
;
CREATE TABLE "ORD"."CUSTOMERS"
(
   ID bigint PRIMARY KEY NOT NULL,
   NAME varchar(255),
   DATE timestamp,
   DESCRIPTION varchar(255),
   BIRTHDAY date DEFAULT CURRENT_DATE,
   RATING numeric,
   NUMBER smallint,
   TEXT longvarchar
)
;
ALTER TABLE "ORD"."ADDRESS"
ADD CONSTRAINT SYS_FK_10098
FOREIGN KEY (CUSTOMER_ID)
REFERENCES "ORD"."CUSTOMERS"(ID)
;
CREATE INDEX SYS_IDX_10102 ON "ORD"."ADDRESS"(CUSTOMER_ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10096_10099 ON "ORD"."ADDRESS"(ID)
;
CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10092_10093 ON "ORD"."CUSTOMERS"(ID)
;
