create schema ORD authorization dba

create table ORD.customers (
	id BIGINT generated by default as identity, 
	name VARCHAR(255),
	date VARCHAR(255) not null,
	genre VARCHAR(1),
	description VARCHAR(255),
		primary key (id))
