create schema ORD authorization dba

create table ORD.customers (
	id BIGINT generated by default as identity, 
	name VARCHAR(255),
		primary key (id))

create table ORD.customers_extended (
	id_e BIGINT, 
	description VARCHAR(255),
		primary key (id_e))	
	
create table ORD.customers_clob (
	id_c BIGINT, 
	number smallint,
	text clob,
		primary key (id_c))	

alter table ord.customers_extended 
	add FOREIGN KEY (id_e) 
	REFERENCES ORD.customers(id)
	
alter table ord.customers_clob
	add FOREIGN KEY (id_c) 
	REFERENCES ORD.customers_extended(id_e)