create schema CTI authorization dba
drop table CTI.ADD_ADDRESS if exists
drop table CTI.CIT_CITY if exists
drop table CTI.EMP_EMPLOYEE if exists
drop table CTI.PER_PERSON if exists
create table CTI.ADD_ADDRESS (ADD_ID integer generated by default as identity (start with 1), ADD_NM_STREET varchar(255), CIT_ID integer, primary key (ADD_ID))
create table CTI.CIT_CITY (CIT_ID integer generated by default as identity (start with 1), CTI_FOUNDATION timestamp, CTI_LAST_UPDATE timestamp, CIT_NM varchar(255), CTI_STATUS bit, primary key (CIT_ID))
create table CTI.EMP_EMPLOYEE (salary double, PER_ID bigint not null, primary key (PER_ID))
create table CTI.PER_PERSON (PER_ID bigint generated by default as identity (start with 1), PER_EMAIL varchar(255), PER_NUMBER bigint, PHO_NUMBER varchar(255), primary key (PER_ID))
alter table CTI.ADD_ADDRESS add constraint FK86B3BA16FBE656F5 foreign key (CIT_ID) references CTI.CIT_CITY
alter table CTI.EMP_EMPLOYEE add constraint FKADCCB865CCA4B2B0 foreign key (PER_ID) references CTI.PER_PERSON