# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: | 
        cp -R userguide/specrunner-core/src/tests/java/* specrunner-core/src/tests/java/ 
        cp -R userguide/specrunner-core/src/tests/resources/* specrunner-core/src/tests/resources/ 
        mvn -U -B --no-transfer-progress package --file specrunner/pom.xml
        mvn -U -B -DskipTests --no-transfer-progress package --file tools/specrunner-tools/pom.xml
        mvn -U -B -DskipTests --no-transfer-progress package --file userguide/specrunner-userguide/pom.xml
