drop schema ORD cascade
create schema ORD authorization dba

create table ORD.customers (
    id BIGINT generated by default as identity, 
    name VARCHAR(255),
    description VARCHAR(255), 
    birthday date default CURRENT_DATE, 
    rating numeric(10,2), 
    number smallint,
    text clob,
        primary key (id))

create table ORD.address (
    id BIGINT generated by default as identity, 
    customer_id integer not null,
    date timestamp,
    address VARCHAR(255) default 'Not informed', 
        primary key (id))
        
alter table ORD.address add foreign key (customer_id) references ORD.customers(id)